### ISSUE TITLE
Likelihood Function

### ISSUE THREAD

**Issue by dangngohai** [sandeepsoni/MHP#2]
Can you explain me the reason of putting an additional epsilon = 1e-50 in your calculation of occurrence likelihood for each occured event?

**Comment by sandeepsoni** [comment]
hmm...I must have done it to avoid `np.log (0)` which can happen when `mu` and `alpha` are 0.

**Comment by dangngohai** [comment]
If i am not misunderstood, it is possible to start calculating recursively R from R(1) rather than from R(0) which assumed to be equal 0?

**Comment by sandeepsoni** [comment]
Yes, that should be possible.

**Comment by dangngohai** [comment]
Just another silly question: what do `src` `curr` in your code stand for? `curr` is current time, the time you consider in the loop? 
And what type of input should i use for  `seq`? Is it list of numpy array type for multi-point processes events?

**Comment by sandeepsoni** [comment]
In MHP, all events are in the form of pairs: whose event is this and at what time this event happened. `src` is the former `curr` is later. `seq` is an iterable of these events.
